### ISSUE TITLE
[Longhaul Test] Hashtag Snapshot Service

### ISSUE THREAD

**Issue by artursouza** [dapr/test-infra#15]
This component will exercise Dapr’s state APIs (not in the context of an Actor). It wakes up every minute and retrieves all keys from Redis state store - not using Dapr’s state APIs, since Dapr does not offer an API to query a range of states from another Dapr application’s state store. Is is expected that only a few dozen keys to be present since the list of hashtags are predefined in this component.
Now key-value pairs are generated for all states and saved via Dapr’s state store API. This service also offers an API to retrieve all keys via a GET method.

Parent: dapr/test-infra#11 

Implement in C#

**Comment by LMWF** [comment]
I propose changing this a bit so we can use more of dapr's apis.  Instead of the snapshot service querying redis directly without dapr, the hashtag actor will open a GET actor api for the snapshot service to call.  The snapshot service will know all hashtags and all sentiments, so it'll be able to ask for all kv value pairs.  All other functionality will match the original description above.

**Comment by artursouza** [comment]
That sounds good to me.
